version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  ".venv/**",
  ".mypy_cache/**",
  ".ruff_cache/**",
  ".pytest_cache/**",
  "dist/**",
  "build/**",
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

   # Keep in sync with ruff line length
  max_line_length = 88

  # DeepSource run mypy as the type checker
  type_checker = "mypy"

[[code_formatters]]
name = "ruff"
enabled = true
